# -*- coding: UTF-8 -*-
# Copyright 2012-2024 Rumma & Ko Ltd
# License: GNU Affero General Public License v3 (see file COPYING for details)

STREETS_IN_EUPEN = ['Aachener Straße',
     'Akazienweg',
     'Alter Malmedyer Weg',
     'Am Bahndamm',
     'Am Berg',
     'Am Waisenbüschchen',
     'Auenweg',
     'Auf dem Spitzberg',
     "Auf'm Rain",
     'August-Thonnar-Str.',
     'Bahnhofsgasse',
     'Bahnhofstraße',
     'Bellmerin',
     'Bennetsborn',
     'Bergkapellstraße',
     'Bergstraße',
     'Binsterweg',
     'Brabantstraße',
     'Buchenweg',
     'Edelstraße',
     'Euregiostraße',
     'Favrunpark',
     'Feldstraße',
     'Fränzel',
     'Gewerbestraße',
     'Gospert',
     'Gülcherstraße',
     'Haagenstraße',
     'Haasberg',
     'Haasstraße',
     'Habsburgerweg',
     'Heidberg',
     'Heidgasse',
     'Heidhöhe',
     'Herbesthaler Straße',
     'Hisselsgasse',
     'Hochstraße',
     'Hook',
     'Hostert',
     'Hufengasse',
     'Hugo-Zimmermann-Str.',
     'Hütte',
     'Hütterprivatweg',
     'Im Peschgen',
     'In den Siepen',
     'Industriestraße',
     'Johannesstraße',
     'Judenstraße',
     'Kaperberg',
     'Kaplan-Arnolds-Str.',
     'Karl-Weiß-Str.',
     'Kehrweg',
     'Kirchgasse',
     'Kirchstraße',
     'Klinkeshöfchen',
     'Kügelgasse',
     'Langesthal',
     'Lascheterweg',
     'Limburgerweg',
     'Lindenweg',
     'Lothringerweg',
     'Malmedyer Straße',
     'Maria-Theresia-Straße',
     'Marktplatz',
     'Monschauer Straße',
     'Mühlenweg',
     'Neustraße',
     'Nikolausfeld',
     'Nispert',
     'Noereth',
     'Obere Ibern',
     'Obere Rottergasse',
     'Oestraße',
     'Olengraben',
     'Panorama',
     'Paveestraße',
     'Peter-Becker-Str.',
     'Rosenweg',
     'Rot-Kreuz-Str.',
     'Rotenberg',
     'Rotenbergplatz',
     'Schilsweg',
     'Schlüsselhof',
     'Schnellewindgasse',
     'Schorberg',
     'Schulstraße',
     'Schönefeld',
     'Selterschlag',
     'Simarstraße',
     'Steinroth',
     'Stendrich',
     'Stockbergerweg',
     'Stockem',
     'Theodor-Mooren-Str.',
     'Untere Ibern',
     'Vervierser Straße',
     'Vossengasse',
     'Voulfeld',
     'Werthplatz',
     'Weserstraße']

# Originally from https://fr.wikipedia.org/wiki/Liste_des_rues_de_Li%C3%A8ge
STREETS_IN_LIEGE = ['Au Péri',
     'Avenue Albert Mahiels',
     'Avenue Blonden',
     'Avenue Charles Rogier',
     'Avenue Maurice Destenay',
     'Avenue Reine Elisabeth',
     'Avenue du Luxembourg',
     'Avenue Émile Digneffe',
     'Boulevard César Thomson',
     'Boulevard Frankignoul',
     'Boulevard Frère-Orban',
     'Boulevard Piercot',
     'Boulevard Saucy',
     "Boulevard d'Avroy",
     'Boulevard de la Constitution',
     'Boulevard de la Sauvenière',
     'Boulevard Émile de Laveleye',
     'Chaussée de Tongres',
     'En Neuvice',
     'Esplanade Saint-Léonard',
     'Féronstrée',
     'Impasse Graindor',
     "Impasse de l'Avenir",
     'Impasse des Ursulines',
     'Impasse du Vieux Pont des Arches',
     'Montagne de Bueren',
     'Passage Lemonnier',
     'Place Crèvecœur',
     'Place Joseph de Bronckart',
     'Place Saint-Barthélemy',
     'Place Saint-Denis',
     'Place Saint-Jacques',
     'Place Saint-Lambert',
     'Place Saint-Michel',
     'Place Saint-Paul',
     'Place Sainte-Véronique',
     'Place Xavier Neujean',
     "Place d'Italie",
     "Place de l'Opéra",
     'Place de la Cathédrale',
     'Place de la République française',
     'Place des Béguinages',
     'Place des Carmes',
     'Place des Franchises',
     'Place des Guillemins',
     'Place des Nations-Unies',
     'Place du 20-Août',
     'Place du Général Leman',
     'Place du Haut-Pré',
     'Place du Marché',
     'Place du Tertre',
     'Potiérue',
     'Quai Bonaparte',
     'Quai Godefroid Kurth',
     'Quai Marcellis',
     'Quai Mativa',
     'Quai Orban',
     'Quai Roosevelt',
     'Quai de Gaulle',
     'Quai de Longdoz',
     'Quai de Maestricht',
     'Quai de Rome',
     "Quai de l'Ourthe",
     'Quai de la Boverie',
     'Quai de la Goffe',
     'Quai de la Ribuée',
     'Quai des Ardennes',
     'Quai des Tanneurs',
     'Quai sur Meuse',
     'Quai Édouard van Beneden',
     'Rue Ambiorix',
     'Rue Armand Stouls',
     'Rue Auguste Hock',
     'Rue Basse-Wez',
     'Rue Beauregard',
     'Rue Bernimolin',
     'Rue Bidaut',
     'Rue Bois Gotha',
     'Rue Bonne-Fortune',
     'Rue Bonne-Nouvelle',
     'Rue Charles Bartholomez',
     'Rue Charles Magnette',
     'Rue Chauve-Souris',
     'Rue Counotte',
     'Rue Cour Petit',
     'Rue Darchis',
     'Rue Dartois',
     'Rue Dehin',
     'Rue Denis Sotiau',
     'Rue Dony',
     'Rue Douffet',
     'Rue En Bois',
     'Rue Ernest Solvay',
     'Rue Ernest de Bavière',
     'Rue Eugène Houdret',
     'Rue Fond Saint-Servais',
     'Rue Frédéric Nyst',
     'Rue Gaston Laboulle',
     'Rue Gaucet',
     'Rue Georges Simenon',
     'Rue Gramme',
     'Rue Grande Bêche',
     'Rue Grétry',
     'Rue Hazinelle',
     'Rue Henri Baron',
     'Rue Henri Koch',
     'Rue Henri Maus',
     'Rue Herman Reuleaux',
     'Rue Hocheporte',
     'Rue Hors-Château',
     'Rue Hullos',
     'Rue Jambe de Bois',
     'Rue Jean Bury',
     'Rue Jean Haust',
     "Rue Jean d'Outremeuse",
     'Rue Joffre',
     'Rue Jonckeu',
     'Rue Jondry',
     'Rue Joseph Demoulin',
     'Rue Joseph Henrion',
     'Rue Joseph Lacroix',
     'Rue Joseph Wauters',
     'Rue Lairesse',
     'Rue Lemille',
     'Rue Libotte',
     'Rue Louis Abry',
     'Rue Louis Fraigneux',
     'Rue Louvrex',
     'Rue Léon Mignon',
     'Rue Léopold',
     'Rue Mississippi',
     'Rue Montagne Sainte-Walburge',
     'Rue Méan',
     'Rue Naniot',
     'Rue Natalis',
     'Rue Oscar Rémy',
     'Rue Paradis',
     'Rue Pierreuse',
     'Rue Plumier',
     "Rue Pont-d'Avroy",
     "Rue Pont-d'Ile",
     'Rue Publémont',
     'Rue Puits-en-Sock',
     'Rue Regnier-Poncelet',
     'Rue Robertson',
     'Rue Roture',
     'Rue Saint-Gilles',
     'Rue Saint-Laurent',
     'Rue Saint-Léonard',
     'Rue Saint-Martin-en-Île',
     'Rue Saint-Michel',
     'Rue Saint-Paul',
     'Rue Saint-Pierre',
     'Rue Saint-Remacle',
     'Rue Saint-Remy',
     'Rue Saint-Séverin',
     'Rue Sainte-Croix',
     'Rue Sainte-Marguerite',
     'Rue Sainte-Marie',
     'Rue Sainte-Véronique',
     'Rue Sainte-Walburge',
     'Rue Soubre',
     "Rue Sous l'Eau",
     'Rue Stappers',
     'Rue Suavius',
     'Rue Tournant Saint-Paul',
     'Rue Toussaint Beaujean',
     'Rue Valdor',
     'Rue Varin',
     'Rue Villette',
     'Rue Volière',
     'Rue Wiertz',
     'Rue aux Frênes',
     "Rue d'Amercoeur",
     "Rue d'Ans",
     "Rue d'Awans",
     "Rue d'Harscamp",
     'Rue de Bruxelles',
     'Rue de Campine',
     'Rue de Chaudfontaine',
     'Rue de Fragnée',
     'Rue de Fétinne',
     'Rue de Harlez',
     'Rue de Hesbaye',
     'Rue de Joie',
     'Rue de Lantin',
     'Rue de Londres',
     'Rue de Namur',
     'Rue de Paris',
     'Rue de Sclessin',
     'Rue de Seraing',
     'Rue de Spa',
     'Rue de Stavelot',
     'Rue de Waroux',
     'Rue de Wazon',
     'Rue de Wetzlar',
     "Rue de l'Abattoir",
     "Rue de l'Académie",
     "Rue de l'Université",
     "Rue de l'Étuve",
     'Rue de la Boucherie (Liège)',
     'Rue de la Casquette',
     'Rue de la Cathédrale',
     'Rue de la Cité',
     'Rue de la Goffe',
     'Rue de la Halle',
     'Rue de la Légia',
     'Rue de la Régence',
     'Rue de la Résistance',
     'Rue de la Sirène',
     'Rue des Abeilles',
     'Rue des Acacias',
     'Rue des Anglais',
     'Rue des Augustins',
     'Rue des Bons Enfants',
     'Rue des Carmes',
     'Rue des Champs',
     'Rue des Clarisses',
     'Rue des Croisiers',
     'Rue des Croix-de-Guerre',
     'Rue des Fontaines-Roland',
     'Rue des Fossés',
     'Rue des Gravillons',
     'Rue des Guillemins',
     'Rue des Houblonnières',
     'Rue des Ixellois',
     'Rue des Jonquilles',
     'Rue des Maraîchers',
     'Rue des Prébendiers',
     'Rue des Remparts',
     'Rue des Rivageois',
     'Rue des Récollets',
     'Rue des Tanneurs',
     'Rue des Tawes',
     'Rue des Urbanistes',
     'Rue des Vennes',
     'Rue des Wallons',
     'Rue du Bosquet',
     'Rue du Coq',
     'Rue du Gros Gland',
     'Rue du Général Bertrand',
     'Rue du Général de Gaulle',
     'Rue du Haut-Pré',
     'Rue du Jardin Botanique',
     'Rue du Laveu',
     'Rue du Mont Saint-Martin',
     'Rue du Palais',
     'Rue du Parc',
     'Rue du Plan Incliné',
     "Rue du Pot d'Or",
     'Rue du Puits',
     'Rue du Terris',
     'Rue du Thier-à-Liège',
     'Rue du Vertbois',
     'Rue du Vieux Mayeur',
     'Rue fond des Tawes',
     'Rue Émile Gérard',
     'Rue Émile Vandervelde',
     'Rue Éracle',
     'Thier de la Chartreuse']

# Originally from https://www.eki.ee/knab/tallinn1.htm
# Peter Päll gave permission to use it here on 2014-11-07.

STREETS_IN_TALLINN = [('1. liin', 'Põhja-Tallinn'),
     ('2. liin', 'Põhja-Tallinn'),
     ('3. liin', 'Põhja-Tallinn'),
     ('4. liin', 'Põhja-Tallinn'),
     ('5. liin', 'Põhja-Tallinn'),
     ('20. Augusti väljak', 'Kesklinn'),
     ('A. H. Tammsaare tee', 'Mustamäe'),
     ('Aarde tn', 'Põhja-Tallinn'),
     ('Aasa tn', 'Kesklinn'),
     ('Aate tn', 'Nõmme'),
     ('Abaja põik', 'Pirita'),
     ('Abaja tn', 'Pirita'),
     ('Abara tn', 'Haabersti'),
     ('Ado Reinvaldi tn', 'Kesklinn'),
     ('Adra tn', 'Nõmme'),
     ('Aedvere tn', 'Haabersti'),
     ('Aedvilja tn', 'Kesklinn'),
     ('Aegna puiestee', 'Lasnamäe'),
     ('Ahingu tn', 'Haabersti'),
     ('Ahju tn', 'Kesklinn'),
     ('Ahtri tn', 'Kesklinn'),
     ('Ahvena tn', 'Haabersti'),
     ('Aia tn', 'Kesklinn'),
     ('Aiandi tn', 'Mustamäe'),
     ('Aianduse tee', 'Pirita'),
     ('Aiatee tn', 'Pirita'),
     ('Aida tn', 'Kesklinn'),
     ('Akadeemia tee', 'Mustamäe'),
     ('Alajaama tn', 'Kristiine'),
     ('Alasi tn', 'Põhja-Tallinn'),
     ('Alemaa tn', 'Haabersti'),
     ('Alevi tn', 'Kesklinn'),
     ('Algi põik', 'Kristiine'),
     ('Algi tn', 'Kristiine'),
     ('Algi tn', 'Mustamäe'),
     ('Allika tn', 'Kesklinn'),
     ('Alliksoo põik', 'Nõmme'),
     ('Alliksoo tn', 'Nõmme'),
     ('Allveelaeva tn', 'Põhja-Tallinn'),
     ('Alvari tn', 'Lasnamäe'),
     ('Amandus Adamsoni tn', 'Kesklinn'),
     ('Amburi tn', 'Põhja-Tallinn'),
     ('Andrekse tee', 'Pirita'),
     ('Angerja tn', 'Põhja-Tallinn'),
     ('Angerpisti tn', 'Lasnamäe'),
     ('Ankru tn', 'Põhja-Tallinn'),
     ('Anni tn', 'Lasnamäe'),
     ('Ants Laikmaa tn', 'Kesklinn'),
     ('Ants Lauteri tn', 'Kesklinn'),
     ('Ao tn', 'Kesklinn'),
     ('Apteegi tn', 'Kesklinn'),
     ('Arbu tn', 'Lasnamäe'),
     ('Armatuuri tn', 'Lasnamäe'),
     ('Arnika tee', 'Pirita'),
     ('Artelli tn', 'Kristiine'),
     ('Artur Kapi tn', 'Kesklinn'),
     ('Aru tn', 'Põhja-Tallinn'),
     ('Arukaskede puiestee', 'Nõmme'),
     ('Asfaldi tn', 'Lasnamäe'),
     ('Astangu tn', 'Haabersti'),
     ('Astla tee', 'Pirita'),
     ('Astri tn', 'Nõmme'),
     ('Asula põik', 'Kesklinn'),
     ('Asula tn', 'Kesklinn'),
     ('Asunduse tn', 'Lasnamäe'),
     ('August Alle tn', 'Kesklinn'),
     ('August Kitzbergi tn', 'Nõmme'),
     ('August Weizenbergi tn', 'Kesklinn'),
     ('Auli tn', 'Kristiine'),
     ('Auna tn', 'Põhja-Tallinn'),
     ('Auru tn', 'Kesklinn'),
     ('Bensiini tn', 'Kesklinn'),
     ('Betooni põik', 'Lasnamäe'),
     ('Betooni tn', 'Lasnamäe'),
     ('Bremeni käik', 'Kesklinn'),
     ('Börsi käik', 'Kesklinn'),
     ('Carl Robert Jakobsoni tn', 'Kesklinn'),
     ('Dunkri tn', 'Kesklinn'),
     ('Edela tn', 'Nõmme'),
     ('Edu tn', 'Nõmme'),
     ('Eduard Bornhöhe tee', 'Pirita'),
     ('Eduard Viiralti tn', 'Kesklinn'),
     ('Eduard Vilde tee', 'Mustamäe'),
     ('Eerikneeme tee', 'Kesklinn'),
     ('Eevardi tn', 'Haabersti'),
     ('Eha tn', 'Kesklinn'),
     ('Ehitajate tee', 'Haabersti'),
     ('Ehitajate tee', 'Mustamäe'),
     ('Ehitajate tee', 'Nõmme'),
     ('Ehte tn', 'Põhja-Tallinn'),
     ('Elektri tn', 'Kristiine'),
     ('Elektroni tn', 'Kristiine'),
     ('Endla tn', 'Kesklinn'),
     ('Endla tn', 'Kristiine'),
     ('Energia tn', 'Kristiine'),
     ('Erika tn', 'Põhja-Tallinn'),
     ('Ernst Särgava allee', 'Pirita'),
     ('Esku tn', 'Pirita'),
     ('Estonia puiestee', 'Kesklinn'),
     ('Falgi tee', 'Kesklinn'),
     ('Ferdinand Johann Wiedemanni tn', 'Kesklinn'),
     ('Filmi tn', 'Kesklinn'),
     ('Filtri tee', 'Kesklinn'),
     ('Forelli tn', 'Kristiine'),
     ('Friedrich Kuhlbarsi tn', 'Kesklinn'),
     ('Friedrich Reinhold Kreutzwaldi tn', 'Kesklinn'),
     ('Friedrich Robert Faehlmanni tn', 'Kesklinn'),
     ('Gaasi tn', 'Lasnamäe'),
     ('Georg Otsa tn', 'Kesklinn'),
     ('Gildi tn', 'Kesklinn'),
     ('Gonsiori tn', 'Kesklinn'),
     ('Graniidi tn', 'Põhja-Tallinn'),
     ('Gümnaasiumi tn', 'Kesklinn'),
     ('Haabersti tn', 'Haabersti'),
     ('Haava tn', 'Nõmme'),
     ('Haaviku põik', 'Pirita'),
     ('Haaviku tee', 'Pirita'),
     ('Hagudi tn', 'Kesklinn'),
     ('Haigru tn', 'Kristiine'),
     ('Haldja tn', 'Nõmme'),
     ('Haljas tee', 'Pirita'),
     ('Halla tn', 'Haabersti'),
     ('Hallikivi tn', 'Nõmme'),
     ('Hallivanamehe tn', 'Kesklinn'),
     ('Halu tn', 'Nõmme'),
     ('Hane tn', 'Kristiine'),
     ('Hange tn', 'Nõmme'),
     ('Hansu tn', 'Haabersti'),
     ('Hao tn', 'Nõmme'),
     ('Haraka tn', 'Kristiine'),
     ('Hargi tn', 'Haabersti'),
     ('Hariduse tn', 'Kesklinn'),
     ('Harju tn', 'Kesklinn'),
     ('Harksaba tn', 'Pirita'),
     ('Harku tn', 'Nõmme'),
     ('Harkumetsa tee', 'Haabersti'),
     ('Hauka tn', 'Kristiine'),
     ('Havi tn', 'Haabersti'),
     ('Heina tn', 'Põhja-Tallinn'),
     ('Heinamaa tn', 'Haabersti'),
     ('Heki tee', 'Pirita'),
     ('Helbe tn', 'Nõmme'),
     ('Helme tn', 'Põhja-Tallinn'),
     ('Helmiku põik', 'Pirita'),
     ('Helmiku tee', 'Pirita'),
     ('Herilase tn', 'Mustamäe'),
     ('Herne tn', 'Kesklinn'),
     ('Hiidtamme tn', 'Nõmme'),
     ('Hiie põik', 'Pirita'),
     ('Hiie tn', 'Pirita'),
     ('Hiiela tee', 'Pirita'),
     ('Hiiu tn', 'Nõmme'),
     ('Hiiu-Maleva tn', 'Nõmme'),
     ('Hiiu-Suurtüki tn', 'Nõmme'),
     ('Hiiumetsa tee', 'Nõmme'),
     ('Hipodroomi tn', 'Põhja-Tallinn'),
     ('Hirve põik', 'Nõmme'),
     ('Hirve tn', 'Nõmme'),
     ('Hobujaama tn', 'Kesklinn'),
     ('Hoburaua tn', 'Haabersti'),
     ('Hobusepea tn', 'Kesklinn'),
     ('Hommiku tn', 'Nõmme'),
     ('Hoo tn', 'Nõmme'),
     ('Hooldekodu tee', 'Lasnamäe'),
     ('Hospidali tn', 'Kesklinn'),
     ('Humala tn', 'Haabersti'),
     ('Hundipea tn', 'Põhja-Tallinn'),
     ('Hunditubaka tee', 'Pirita'),
     ('Hälli põik', 'Haabersti'),
     ('Hälli tn', 'Haabersti'),
     ('Hämar tee', 'Pirita'),
     ('Hämariku tn', 'Nõmme'),
     ('Härgmäe tn', 'Haabersti'),
     ('Härjapea tn', 'Põhja-Tallinn'),
     ('Härmatise tn', 'Haabersti'),
     ('Hõbeda tn', 'Kesklinn'),
     ('Hõbekuuse tee', 'Pirita'),
     ('Hõberebase tn', 'Nõmme'),
     ('Hõimu tn', 'Nõmme'),
     ('Hüübi tn', 'Kristiine'),
     ('Ida tee', 'Pirita'),
     ('Idakaare põik', 'Nõmme'),
     ('Idakaare tn', 'Nõmme'),
     ('Ilmarise tn', 'Nõmme'),
     ('Ilo tn', 'Nõmme'),
     ('Ilvese tn', 'Nõmme'),
     ('Imanta tn', 'Kesklinn'),
     ('Inseneri tn', 'Kesklinn'),
     ('Invaliidi tn', 'Kesklinn'),
     ('Irusilla tn', 'Pirita'),
     ('Islandi väljak', 'Kesklinn'),
     ('Iva tn', 'Mustamäe'),
     ('Jaagu tn', 'Haabersti'),
     ('Jaama tn', 'Nõmme'),
     ('Jaan Koorti tn', 'Lasnamäe'),
     ('Jaan Poska tn', 'Kesklinn'),
     ('Jaaniku tn', 'Pirita'),
     ('Jaanilille tee', 'Pirita'),
     ('Jahe tee', 'Pirita'),
     ('Jahimehe põik', 'Pirita'),
     ('Jahimehe tee', 'Pirita'),
     ('Jahu tn', 'Põhja-Tallinn'),
     ('Jakob Mändmetsa tn', 'Nõmme'),
     ('Jakob Pärna tn', 'Kesklinn'),
     ('Jakobi tn', 'Kesklinn'),
     ('Jalaka tn', 'Nõmme'),
     ('Jalami tn', 'Haabersti'),
     ('Jasmiini tee', 'Pirita'),
     ('Joa tn', 'Kesklinn'),
     ('Johann Köleri tn', 'Kesklinn'),
     ('Johann Voldemar Jannseni tn', 'Nõmme'),
     ('Johannes Kappeli tn', 'Kesklinn'),
     ('Joone tn', 'Haabersti'),
     ('Jugapuu põik', 'Pirita'),
     ('Jugapuu tee', 'Pirita'),
     ('Juhan Kunderi põik', 'Kesklinn'),
     ('Juhan Kunderi tn', 'Kesklinn'),
     ('Juhan Smuuli tee', 'Lasnamäe'),
     ('Juhan Sütiste tee', 'Mustamäe'),
     ('Juhkentali tn', 'Kesklinn'),
     ('Juhtme tn', 'Kesklinn'),
     ('Jumika tee', 'Pirita'),
     ('Juurdeveo tn', 'Kesklinn'),
     ('Järve tn', 'Kristiine'),
     ('Järvekalda tee', 'Haabersti'),
     ('Järveotsa tee', 'Haabersti'),
     ('Järvevana tee', 'Kesklinn'),
     ('Jääraku põik', 'Pirita'),
     ('Jääraku tee', 'Pirita'),
     ('Jõe tn', 'Kesklinn'),
     ('Jõekalda tn', 'Pirita'),
     ('Jõeküla tee', 'Haabersti'),
     ('Jõeoti tn', 'Haabersti'),
     ('Jõhvika tn', 'Nõmme'),
     ('Jüri Vilmsi tn', 'Kesklinn'),
     ('Kaabli tn', 'Kesklinn'),
     ('Kaare tn', 'Nõmme'),
     ('Kaarla tn', 'Nõmme'),
     ('Kaarlepere tn', 'Haabersti'),
     ('Kaarli puiestee', 'Kesklinn'),
     ('Kaarna tn', 'Kristiine'),
     ('Kaaruti tn', 'Haabersti'),
     ('Kaasiku tn', 'Nõmme'),
     ('Kabli tn', 'Haabersti'),
     ('Kadaka puiestee', 'Nõmme'),
     ('Kadaka tee', 'Kristiine'),
     ('Kadri tee', 'Kesklinn'),
     ('Kaera tn', 'Põhja-Tallinn'),
     ('Kaeravälja tn', 'Haabersti'),
     ('Kaevu tn', 'Nõmme'),
     ('Kaevuri tn', 'Põhja-Tallinn'),
     ('Kagu tn', 'Nõmme'),
     ('Kaheküla tee', 'Haabersti'),
     ('Kahlu tn', 'Haabersti'),
     ('Kahu tn', 'Lasnamäe'),
     ('Kahva tn', 'Haabersti'),
     ('Kai tn', 'Kesklinn'),
     ('Kailu tee', 'Pirita'),
     ('Kaisla tn', 'Haabersti'),
     ('Kaitse tn', 'Nõmme'),
     ('Kaja tn', 'Nõmme'),
     ('Kajaka tn', 'Kristiine'),
     ('Kakumäe tee', 'Haabersti'),
     ('Kaladi tn', 'Haabersti'),
     ('Kalamehe tee', 'Pirita'),
     ('Kalaranna tn', 'Põhja-Tallinn'),
     ('Kalasadama tn', 'Põhja-Tallinn'),
     ('Kalavälja tee', 'Kesklinn'),
     ('Kalda tn', 'Nõmme'),
     ('Kalevala tn', 'Nõmme'),
     ('Kalevi tn', 'Põhja-Tallinn'),
     ('Kalevipoja põik', 'Lasnamäe'),
     ('Kalevipoja tn', 'Lasnamäe'),
     ('Kaljase tn', 'Kesklinn'),
     ('Kalju tn', 'Põhja-Tallinn'),
     ('Kallaste tn', 'Pirita'),
     ('Kalmistu tee', 'Nõmme'),
     ('Kalmuse tee', 'Pirita'),
     ('Kaluri tn', 'Põhja-Tallinn'),
     ('Kammelja tn', 'Haabersti'),
     ('Kampri tn', 'Kristiine'),
     ('Kanali tee', 'Kesklinn'),
     ('Kanarbiku tn', 'Nõmme'),
     ('Kandle tn', 'Nõmme'),
     ('Kanepi tn', 'Põhja-Tallinn'),
     ('Kangru tn', 'Põhja-Tallinn'),
     ('Kannikese tn', 'Kristiine'),
     ('Kannustiiva tn', 'Pirita'),
     ('Kantsi tn', 'Lasnamäe'),
     ('Kanuti tn', 'Kesklinn'),
     ('Karamelli tn', 'Kesklinn'),
     ('Kari tn', 'Põhja-Tallinn'),
     ('Karjamaa tn', 'Põhja-Tallinn'),
     ('Karl August Hermanni tn', 'Kesklinn'),
     ('Karnapi tee', 'Kesklinn'),
     ('Karsti tn', 'Mustamäe'),
     ('Karu tn', 'Kesklinn'),
     ('Karukella tee', 'Pirita'),
     ('Karusambla tn', 'Nõmme'),
     ('Karuse tn', 'Nõmme'),
     ('Karusmarja tn', 'Nõmme'),
     ('Kase tn', 'Pirita'),
     ('Kaskede puiestee', 'Nõmme'),
     ('Kassi tn', 'Mustamäe'),
     ('Kassikäpa tee', 'Pirita'),
     ('Kastani tn', 'Nõmme'),
     ('Kaste tn', 'Nõmme'),
     ('Kasteheina tn', 'Nõmme'),
     ('Kastevarre tee', 'Pirita'),
     ('Kastiku tee', 'Pirita'),
     ('Kasvu tn', 'Kristiine'),
     ('Katariina käik', 'Kesklinn'),
     ('Katleri tn', 'Lasnamäe'),
     ('Katusepapi tn', 'Lasnamäe'),
     ('Kauba tn', 'Kesklinn'),
     ('Kaubamaja tn', 'Kesklinn'),
     ('Kauge tn', 'Nõmme'),
     ('Kauka tn', 'Kesklinn'),
     ('Kauna tn', 'Kesklinn'),
     ('Kaunis tn', 'Pirita'),
     ('Kaupmehe tn', 'Kesklinn'),
     ('Kauri tn', 'Kristiine'),
     ('Keava tn', 'Kesklinn'),
     ('Kedriku tn', 'Pirita'),
     ('Keemia tn', 'Kristiine'),
     ('Keeru tee', 'Pirita'),
     ('Keevise tn', 'Lasnamäe'),
     ('Keldrimäe tn', 'Kesklinn'),
     ('Kelluka tee', 'Pirita'),
     ('Kentmanni põik', 'Kesklinn'),
     ('Kentmanni tn', 'Kesklinn'),
     ('Kesk-Ameerika tn', 'Kesklinn'),
     ('Kesk-Kalamaja tn', 'Põhja-Tallinn'),
     ('Kesk-Luha tn', 'Kesklinn'),
     ('Kesk-Sõjamäe tn', 'Lasnamäe'),
     ('Keskküla tn', 'Haabersti'),
     ('Kesktee', 'Pirita'),
     ('Keskuse tn', 'Mustamäe'),
     ('Kessi tn', 'Haabersti'),
     ('Ketraja tn', 'Põhja-Tallinn'),
     ('Ketta tn', 'Põhja-Tallinn'),
     ('Kevade tn', 'Kesklinn'),
     ('Kibuvitsa tn', 'Kristiine'),
     ('Kihnu tn', 'Lasnamäe'),
     ('Kiige tn', 'Nõmme'),
     ('Kiikri tn', 'Kesklinn'),
     ('Kiili tn', 'Mustamäe'),
     ('Kiini tn', 'Haabersti'),
     ('Kiire tn', 'Kesklinn'),
     ('Kiisa tn', 'Kesklinn'),
     ('Kiive tn', 'Lasnamäe'),
     ('Kilbi tn', 'Põhja-Tallinn'),
     ('Kilde tn', 'Haabersti'),
     ('Killustiku tn', 'Lasnamäe'),
     ('Kilu tn', 'Haabersti'),
     ('Kinga tn', 'Kesklinn'),
     ('Kirde tn', 'Nõmme'),
     ('Kiriku plats', 'Kesklinn'),
     ('Kiriku põik', 'Kesklinn'),
     ('Kiriku tn', 'Kesklinn'),
     ('Kirilase tn', 'Pirita'),
     ('Kirsi tn', 'Kristiine'),
     ('Kitsas tn', 'Nõmme'),
     ('Kitseküla tn', 'Kesklinn'),
     ('Kiuru tn', 'Kristiine'),
     ('Kivi tn', 'Nõmme'),
     ('Kiviaia tee', 'Pirita'),
     ('Kivila tn', 'Lasnamäe'),
     ('Kivimurru tn', 'Lasnamäe'),
     ('Kivimäe tn', 'Nõmme'),
     ('Kiviranna tee', 'Haabersti'),
     ('Kiviriku tn', 'Lasnamäe'),
     ('Kivisilla tn', 'Kesklinn'),
     ('Klaasi tn', 'Põhja-Tallinn'),
     ('Kloostri tee', 'Pirita'),
     ('Kloostrimetsa tee', 'Pirita'),
     ('Kodu tn', 'Kesklinn'),
     ('Koge tn', 'Kesklinn'),
     ('Kohila tn', 'Kesklinn'),
     ('Kohtu tn', 'Kesklinn'),
     ('Koidiku tn', 'Nõmme'),
     ('Koidu tn', 'Kesklinn'),
     ('Kolde puiestee', 'Põhja-Tallinn'),
     ('Koldrohu tee', 'Pirita'),
     ('Kollane tn', 'Kesklinn'),
     ('Komandandi tee', 'Kesklinn'),
     ('Komeedi tn', 'Kesklinn'),
     ('Konstantin Türnpu tn', 'Kesklinn'),
     ('Koogu tn', 'Haabersti'),
     ('Kooli tn', 'Kesklinn'),
     ('Kopli tn', 'Põhja-Tallinn'),
     ('Kopliranna tn', 'Põhja-Tallinn'),
     ('Korese tn', 'Haabersti'),
     ('Korgi tn', 'Kesklinn'),
     ('Kose põik', 'Pirita'),
     ('Kose tee', 'Pirita'),
     ('Kosemetsa tn', 'Pirita'),
     ('Koskla tn', 'Kristiine'),
     ('Kotermaa tn', 'Haabersti'),
     ('Kotka tn', 'Kristiine'),
     ('Kotkapoja tn', 'Kristiine'),
     ('Kotlepi tn', 'Haabersti'),
     ('Kotzebue tn', 'Põhja-Tallinn'),
     ('Kraavi tn', 'Nõmme'),
     ('Kreegi tn', 'Nõmme'),
     ('Kressi tee', 'Pirita'),
     ('Kriibi tn', 'Pirita'),
     ('Kriidi tn', 'Lasnamäe'),
     ('Kristeni tn', 'Haabersti'),
     ('Kristiina tn', 'Kesklinn'),
     ('Kristjan Kärberi tn', 'Lasnamäe'),
     ('Kristjan Raua tn', 'Nõmme'),
     ('Kruusa tn', 'Nõmme'),
     ('Kruusaranna tee', 'Haabersti'),
     ('Kubu tn', 'Haabersti'),
     ('Kudu tn', 'Haabersti'),
     ('Kuhja tn', 'Haabersti'),
     ('Kuiv tn', 'Nõmme'),
     ('Kuke tn', 'Kesklinn'),
     ('Kuklase tn', 'Mustamäe'),
     ('Kuldnoka tn', 'Kristiine'),
     ('Kuldtiiva tn', 'Pirita'),
     ('Kuljuse tn', 'Nõmme'),
     ('Kullassepa tn', 'Kesklinn'),
     ('Kullerkupu tn', 'Kristiine'),
     ('Kullese tn', 'Pirita'),
     ('Kulli tn', 'Kristiine'),
     ('Kumalase tn', 'Nõmme'),
     ('Kume tn', 'Nõmme'),
     ('Kummeli tee', 'Pirita'),
     ('Kungla tn', 'Põhja-Tallinn'),
     ('Kuninga tn', 'Kesklinn'),
     ('Kupra tee', 'Pirita'),
     ('Kura tn', 'Nõmme'),
     ('Kure tn', 'Kristiine'),
     ('Kuremarja tn', 'Nõmme'),
     ('Kurepõllu tn', 'Lasnamäe'),
     ('Kurereha tee', 'Pirita'),
     ('Kurikneeme tee', 'Kesklinn'),
     ('Kuristiku tn', 'Kesklinn'),
     ('Kurmu tn', 'Haabersti'),
     ('Kurni põik', 'Nõmme'),
     ('Kurni tn', 'Nõmme'),
     ('Kuru tn', 'Nõmme'),
     ('Kuslapuu tn', 'Pirita'),
     ('Kuukressi tee', 'Pirita'),
     ('Kuuli tn', 'Lasnamäe'),
     ('Kuunari tn', 'Kesklinn'),
     ('Kuuse tn', 'Nõmme'),
     ('Kuusenõmme tee', 'Pirita'),
     ('Kuusiku tee', 'Pirita'),
     ('Kvartsi tn', 'Nõmme'),
     ('Käba tn', 'Haabersti'),
     ('Käbi tn', 'Nõmme'),
     ('Käbliku tn', 'Kristiine'),
     ('Käia tn', 'Haabersti'),
     ('Kännu tn', 'Kristiine'),
     ('Käo põik', 'Kristiine'),
     ('Käo tn', 'Kristiine'),
     ('Käokannu tee', 'Pirita'),
     ('Käokeele tee', 'Pirita'),
     ('Käokäpa tee', 'Pirita'),
     ('Käolina tn', 'Nõmme'),
     ('Kärbi tn', 'Nõmme'),
     ('Kärestiku tn', 'Pirita'),
     ('Kärje tn', 'Nõmme'),
     ('Kärneri tn', 'Haabersti'),
     ('Käru tn', 'Kesklinn'),
     ('Kätki tn', 'Haabersti'),
     ('Käänu tn', 'Haabersti'),
     ('Kõdra tee', 'Pirita'),
     ('Kõivu põik', 'Pirita'),
     ('Kõivu tee', 'Pirita'),
     ('Kõla tn', 'Nõmme'),
     ('Kõlviku põik', 'Pirita'),
     ('Kõlviku tee', 'Pirita'),
     ('Kõnnu tn', 'Nõmme'),
     ('Kõrge tn', 'Nõmme'),
     ('Kõrgepinge tn', 'Haabersti'),
     ('Kõrkja tee', 'Pirita'),
     ('Kõrre tn', 'Põhja-Tallinn'),
     ('Kõue tn', 'Nõmme'),
     ('Kõver tn', 'Nõmme'),
     ('Köie tn', 'Põhja-Tallinn'),
     ('Köömne tn', 'Haabersti'),
     ('Külaniidu tee', 'Kesklinn'),
     ('Külma tn', 'Haabersti'),
     ('Külmallika põik', 'Nõmme'),
     ('Külmallika tn', 'Nõmme'),
     ('Külvi tn', 'Nõmme'),
     ('Künka tn', 'Nõmme'),
     ('Künkamaa tn', 'Haabersti'),
     ('Künnapuu tn', 'Pirita'),
     ('Künni tn', 'Nõmme'),
     ('Küti tn', 'Põhja-Tallinn'),
     ('Küüvitsa tee', 'Pirita'),
     ('Laagna tee', 'Lasnamäe'),
     ('Laane tn', 'Nõmme'),
     ('Laaniku tn', 'Nõmme'),
     ('Laboratooriumi tn', 'Kesklinn'),
     ('Laeva tn', 'Kesklinn'),
     ('Laevastiku tn', 'Põhja-Tallinn'),
     ('Lagedi tee', 'Lasnamäe'),
     ('Lageloo tn', 'Lasnamäe'),
     ('Lagle puiestee', 'Kristiine'),
     ('Lahe tn', 'Kesklinn'),
     ('Lai tn', 'Kesklinn'),
     ('Laiaküla tee', 'Pirita'),
     ('Laine tn', 'Kristiine'),
     ('Laki tn', 'Kristiine'),
     ('Lambi tn', 'Kesklinn'),
     ('Landi tn', 'Haabersti'),
     ('Laose tn', 'Haabersti'),
     ('Lasnamäe tn', 'Lasnamäe'),
     ('Laste tn', 'Nõmme'),
     ('Lastekodu tn', 'Kesklinn'),
     ('Latika tn', 'Haabersti'),
     ('Lauka tn', 'Nõmme'),
     ('Lauliku tn', 'Nõmme'),
     ('Laulu tn', 'Nõmme'),
     ('Laulupeo tn', 'Kesklinn'),
     ('Lauri tee', 'Pirita'),
     ('Lauripere tn', 'Haabersti'),
     ('Lavamaa tn', 'Lasnamäe'),
     ('Lee tn', 'Haabersti'),
     ('Leediku tn', 'Pirita'),
     ('Leedri tee', 'Pirita'),
     ('Leegi tn', 'Nõmme'),
     ('Leesika tn', 'Nõmme'),
     ('Leete tn', 'Kesklinn'),
     ('Leevikese tn', 'Kristiine'),
     ('Lehe tn', 'Kristiine'),
     ('Lehiku tee', 'Pirita'),
     ('Lehise tn', 'Pirita'),
     ('Lehiste puiestee', 'Nõmme'),
     ('Lehola tn', 'Nõmme'),
     ('Lehtmäe tn', 'Haabersti'),
     ('Lehtpuu tn', 'Nõmme'),
     ('Lehtri tn', 'Mustamäe'),
     ('Leigeri tn', 'Põhja-Tallinn'),
     ('Leina tn', 'Nõmme'),
     ('Lelle tn', 'Kesklinn'),
     ('Lembitu tn', 'Kesklinn'),
     ('Lemle tn', 'Haabersti'),
     ('Lemmiku põik', 'Nõmme'),
     ('Lemmiku tn', 'Nõmme'),
     ('Lennujaama tee', 'Lasnamäe'),
     ('Lennuki tn', 'Kesklinn'),
     ('Lennusadama tn', 'Põhja-Tallinn'),
     ('Lepa põik', 'Pirita'),
     ('Lepa tn', 'Pirita'),
     ('Lepatriinu tn', 'Mustamäe'),
     ('Lepiku tee', 'Pirita'),
     ('Lesta tn', 'Haabersti'),
     ('Liblika tn', 'Kristiine'),
     ('Liikuri tn', 'Lasnamäe'),
     ('Liilia tee', 'Pirita'),
     ('Liimi tn', 'Kristiine'),
     ('Liinivahe tn', 'Põhja-Tallinn'),
     ('Liipri tn', 'Nõmme'),
     ('Liiva tn', 'Nõmme'),
     ('Liivalaia tn', 'Kesklinn'),
     ('Liivaluite tn', 'Nõmme'),
     ('Liivametsa tn', 'Nõmme'),
     ('Liivamäe tn', 'Kesklinn'),
     ('Liivaoja tn', 'Kesklinn'),
     ('Liivaranna tee', 'Haabersti'),
     ('Liiviku tn', 'Nõmme'),
     ('Lille tn', 'Kristiine'),
     ('Lilleherne tee', 'Pirita'),
     ('Lillevälja tn', 'Haabersti'),
     ('Lina tn', 'Põhja-Tallinn'),
     ('Linda tn', 'Põhja-Tallinn'),
     ('Lindakivi puiestee', 'Lasnamäe'),
     ('Linnamäe tee', 'Lasnamäe'),
     ('Linnu tee', 'Kristiine'),
     ('Linnuse tee', 'Lasnamäe'),
     ('Lobjaka tn', 'Haabersti'),
     ('Lodjapuu tee', 'Pirita'),
     ('Lodumetsa tee', 'Pirita'),
     ('Logi tn', 'Kesklinn'),
     ('Lohu tn', 'Nõmme'),
     ('Loigu tn', 'Haabersti'),
     ('Loite tn', 'Kesklinn'),
     ('Loitsu tn', 'Lasnamäe'),
     ('Loo tn', 'Kristiine'),
     ('Loode põik', 'Kesklinn'),
     ('Loode tn', 'Kesklinn'),
     ('Looga tn', 'Haabersti'),
     ('Looklev tee', 'Pirita'),
     ('Loometsa tn', 'Lasnamäe'),
     ('Loomuse tn', 'Haabersti'),
     ('Loopealse puiestee', 'Lasnamäe'),
     ('Lootsi tn', 'Kesklinn'),
     ('Lootuse puiestee', 'Nõmme'),
     ('Lootuse põik', 'Nõmme'),
     ('Lossi plats', 'Kesklinn'),
     ('Lossi tn', 'Nõmme'),
     ('Lubja tn', 'Kesklinn'),
     ('Luha tn', 'Kesklinn'),
     ('Luige tn', 'Kristiine'),
     ('Luise tn', 'Kesklinn'),
     ('Luisu tn', 'Haabersti'),
     ('Luite tn', 'Kesklinn'),
     ('Luku tn', 'Kesklinn'),
     ('Lume tn', 'Põhja-Tallinn'),
     ('Lumikellukese tee', 'Pirita'),
     ('Lumiku tn', 'Pirita'),
     ('Lummu tn', 'Lasnamäe'),
     ('Luste tn', 'Põhja-Tallinn'),
     ('Lydia Koidula tn', 'Kesklinn'),
     ('Läike tn', 'Nõmme'),
     ('Lätte tn', 'Kesklinn'),
     ('Lääne tee', 'Pirita'),
     ('Läänekaare tn', 'Nõmme'),
     ('Läänemere tee', 'Lasnamäe'),
     ('Lõhe tn', 'Haabersti'),
     ('Lõhmuse põik', 'Pirita'),
     ('Lõhmuse tee', 'Pirita'),
     ('Lõikuse tn', 'Nõmme'),
     ('Lõime tn', 'Põhja-Tallinn'),
     ('Lõimise tn', 'Haabersti'),
     ('Lõkke tn', 'Kesklinn'),
     ('Lõo tn', 'Nõmme'),
     ('Lõokese tn', 'Kristiine'),
     ('Lõosilma tee', 'Pirita'),
     ('Lõuka tn', 'Haabersti'),
     ('Lõuna tn', 'Nõmme'),
     ('Lõvi tn', 'Nõmme'),
     ('Lõõtsa tn', 'Lasnamäe'),
     ('Lühike jalg', 'Kesklinn'),
     ('Lühike tn', 'Nõmme'),
     ('Lükati tee', 'Pirita'),
     ('Lüli tn', 'Kesklinn'),
     ('Lüüsi tn', 'Kesklinn'),
     ('Maakri tn', 'Kesklinn'),
     ('Maarjaheina tn', 'Kesklinn'),
     ('Maarjamäe tn', 'Kesklinn'),
     ('Maasika tn', 'Kristiine'),
     ('Madala tn', 'Põhja-Tallinn'),
     ('Madalmaa tn', 'Kesklinn'),
     ('Madara tn', 'Kristiine'),
     ('Magasini tn', 'Kesklinn'),
     ('Magdaleena tn', 'Kesklinn'),
     ('Mahla tn', 'Nõmme'),
     ('Mahtra tn', 'Lasnamäe'),
     ('Mai põik', 'Nõmme'),
     ('Mai tn', 'Nõmme'),
     ('Maikellukese tee', 'Pirita'),
     ('Mailase tee', 'Pirita'),
     ('Maimu tn', 'Haabersti'),
     ('Maisi tn', 'Põhja-Tallinn'),
     ('Mait Metsanurga tn', 'Nõmme'),
     ('Majaka põik', 'Lasnamäe'),
     ('Majaka tn', 'Lasnamäe'),
     ('Maleva põik', 'Põhja-Tallinn'),
     ('Maleva tn', 'Põhja-Tallinn'),
     ('Malmi tn', 'Põhja-Tallinn'),
     ('Maneeži tn', 'Kesklinn'),
     ('Manufaktuuri tn', 'Põhja-Tallinn'),
     ('Marana tn', 'Lasnamäe'),
     ('Marati tn', 'Põhja-Tallinn'),
     ('Mardi tn', 'Kesklinn'),
     ('Mardipere tn', 'Haabersti'),
     ('Marja tn', 'Kristiine'),
     ('Marjamaa tn', 'Haabersti'),
     ('Marsi tn', 'Kristiine'),
     ('Marta tn', 'Kesklinn'),
     ('Martsa tn', 'Lasnamäe'),
     ('Masina tn', 'Kesklinn'),
     ('Masti tn', 'Pirita'),
     ('Matka tee', 'Pirita'),
     ('Meeliku tn', 'Lasnamäe'),
     ('Meeruse tn', 'Põhja-Tallinn'),
     ('Mehaanika põik', 'Kristiine'),
     ('Mehaanika tn', 'Kristiine'),
     ('Meika tn', 'Kristiine'),
     ('Meistri tn', 'Haabersti'),
     ('Meleka tn', 'Kristiine'),
     ('Mere puiestee', 'Kesklinn'),
     ('Merelahe tee', 'Põhja-Tallinn'),
     ('Meremehe tee', 'Pirita'),
     ('Merihärja tn', 'Haabersti'),
     ('Merikanni tn', 'Pirita'),
     ('Merimetsa tee', 'Põhja-Tallinn'),
     ('Merinõela tn', 'Haabersti'),
     ('Merirahu tn', 'Haabersti'),
     ('Merivälja tee', 'Pirita'),
     ('Mesika põik', 'Pirita'),
     ('Mesika tee', 'Pirita'),
     ('Mesila tn', 'Nõmme'),
     ('Metalli tn', 'Kristiine'),
     ('Metsa põik', 'Nõmme'),
     ('Metsa tn', 'Nõmme'),
     ('Metsakooli põik', 'Pirita'),
     ('Metsakooli tee', 'Pirita'),
     ('Metsavahi põik', 'Pirita'),
     ('Metsavahi tee', 'Pirita'),
     ('Metsaveere tn', 'Nõmme'),
     ('Metsise tn', 'Kristiine'),
     ('Metsniku tee', 'Pirita'),
     ('Miina Härma tn', 'Lasnamäe'),
     ('Mineraali tn', 'Kristiine'),
     ('Mirta tn', 'Haabersti'),
     ('Moonalao tn', 'Haabersti'),
     ('Mooni tn', 'Kristiine'),
     ('Moora tn', 'Nõmme'),
     ('Moora umbtänav', 'Nõmme'),
     ('Moskva puiestee', 'Lasnamäe'),
     ('Mugula tee', 'Pirita'),
     ('Muhu tn', 'Lasnamäe'),
     ('Mulla põik', 'Põhja-Tallinn'),
     ('Mulla tn', 'Põhja-Tallinn'),
     ('Munga tn', 'Kesklinn'),
     ('Muraka tn', 'Nõmme'),
     ('Mureli tn', 'Haabersti'),
     ('Muru tn', 'Nõmme'),
     ('Mustakivi tee', 'Lasnamäe'),
     ('Mustamäe tee', 'Kristiine'),
     ('Mustika tn', 'Nõmme'),
     ('Mustjuure tn', 'Haabersti'),
     ('Mustjõe põik', 'Haabersti'),
     ('Mustjõe tn', 'Haabersti'),
     ('Muti tn', 'Kristiine'),
     ('Muuga tee', 'Pirita'),
     ('Muuluka tn', 'Nõmme'),
     ('Mäe tn', 'Lasnamäe'),
     ('Mäealuse tn', 'Mustamäe'),
     ('Mäekalda tn', 'Kesklinn'),
     ('Mäekõrtsi tn', 'Haabersti'),
     ('Mäepealse tn', 'Mustamäe'),
     ('Mäepere tn', 'Haabersti'),
     ('Mägra tn', 'Nõmme'),
     ('Mähe tee', 'Pirita'),
     ('Mähe-Kaasiku tee', 'Pirita'),
     ('Mängu tn', 'Nõmme'),
     ('Männi tn', 'Nõmme'),
     ('Männiku tee', 'Nõmme'),
     ('Männiliiva tn', 'Mustamäe'),
     ('Männimetsa põik', 'Nõmme'),
     ('Männimetsa tee', 'Nõmme'),
     ('Mõigu tn', 'Kesklinn'),
     ('Mõisa tn', 'Haabersti'),
     ('Mõisapõllu tn', 'Haabersti'),
     ('Mõrra tee', 'Pirita'),
     ('Mõtuse tn', 'Kristiine'),
     ('Mõõna tee', 'Pirita'),
     ('Möldre tee', 'Nõmme'),
     ('Mündi tn', 'Kesklinn'),
     ('Müta tn', 'Haabersti'),
     ('Müürivahe tn', 'Kesklinn'),
     ('Naadi tee', 'Pirita'),
     ('Naaritsa tn', 'Nõmme'),
     ('Nabra tn', 'Põhja-Tallinn'),
     ('Naeri tn', 'Kesklinn'),
     ('Nafta tn', 'Kesklinn'),
     ('Naistepuna tee', 'Pirita'),
     ('Narva maantee', 'Kesklinn'),
     ('Nata tn', 'Haabersti'),
     ('Neeme põik', 'Põhja-Tallinn'),
     ('Neeme tn', 'Põhja-Tallinn'),
     ('Neemiku tn', 'Lasnamäe'),
     ('Neiuvaiba tee', 'Pirita'),
     ('Nelgi tn', 'Nõmme'),
     ('Nepi tn', 'Kristiine'),
     ('Nigli tn', 'Haabersti'),
     ('Niguliste tn', 'Kesklinn'),
     ('Niidi põik', 'Põhja-Tallinn'),
     ('Niidi tn', 'Põhja-Tallinn'),
     ('Niidu tee', 'Pirita'),
     ('Niine põik', 'Põhja-Tallinn'),
     ('Niine tn', 'Põhja-Tallinn'),
     ('Nikolai von Glehni põik', 'Nõmme'),
     ('Nikolai von Glehni tn', 'Nõmme'),
     ('Nirgi tn', 'Kristiine'),
     ('Nisu tn', 'Põhja-Tallinn'),
     ('Nooda tee', 'Haabersti'),
     ('Noole tn', 'Põhja-Tallinn'),
     ('Noorkuu tn', 'Haabersti'),
     ('Nugise tn', 'Nõmme'),
     ('Nuia tn', 'Lasnamäe'),
     ('Nulu tn', 'Pirita'),
     ('Nunne tn', 'Kesklinn'),
     ('Nurklik tn', 'Haabersti'),
     ('Nurme tn', 'Nõmme'),
     ('Nurmenuku tee', 'Pirita'),
     ('Nurmiku põik', 'Pirita'),
     ('Nurmiku tee', 'Pirita'),
     ('Näituse tn', 'Nõmme'),
     ('Näsiniine tee', 'Pirita'),
     ('Nõeliku tn', 'Haabersti'),
     ('Nõgikikka tn', 'Haabersti'),
     ('Nõlva tn', 'Põhja-Tallinn'),
     ('Nõmme põik', 'Kristiine'),
     ('Nõmme tee', 'Kristiine'),
     ('Nõmme-Kase tn', 'Nõmme'),
     ('Nõo tee', 'Pirita'),
     ('Nõva tn', 'Nõmme'),
     ('Oa tn', 'Kesklinn'),
     ('Oblika tee', 'Pirita'),
     ('Oda tn', 'Põhja-Tallinn'),
     ('Odra tn', 'Kesklinn'),
     ('Oja tn', 'Haabersti'),
     ('Ojakääru tn', 'Haabersti'),
     ('Ojaveere tn', 'Haabersti'),
     ('Oksa tn', 'Kristiine'),
     ('Olevi põik', 'Nõmme'),
     ('Olevi tn', 'Nõmme'),
     ('Olevimägi', 'Kesklinn'),
     ('Oleviste tn', 'Kesklinn'),
     ('Oomi tn', 'Kesklinn'),
     ('Orase tn', 'Põhja-Tallinn'),
     ('Orava tn', 'Nõmme'),
     ('Oru tn', 'Kesklinn'),
     ('Osja tee', 'Pirita'),
     ('Osmussaare tn', 'Lasnamäe'),
     ('Oti tn', 'Haabersti'),
     ('Otsatalu tn', 'Haabersti'),
     ('Otse tn', 'Haabersti'),
     ('Paadi tn', 'Kesklinn'),
     ('Paagi tn', 'Põhja-Tallinn'),
     ('Paakspuu tee', 'Pirita'),
     ('Paasiku tn', 'Lasnamäe'),
     ('Paavli tn', 'Põhja-Tallinn'),
     ('Padriku tee', 'Pirita'),
     ('Padu tn', 'Nõmme'),
     ('Pae tn', 'Lasnamäe'),
     ('Paekaare tn', 'Lasnamäe'),
     ('Paekalda tn', 'Lasnamäe'),
     ('Paekivi tn', 'Lasnamäe'),
     ('Paepargi tn', 'Lasnamäe'),
     ('Paevälja puiestee', 'Lasnamäe'),
     ('Pagari tn', 'Kesklinn'),
     ('Paide tn', 'Kesklinn'),
     ('Paiste tn', 'Nõmme'),
     ('Paisu tn', 'Pirita'),
     ('Paju tn', 'Pirita'),
     ('Pajude puiestee', 'Nõmme'),
     ('Pajulille tee', 'Pirita'),
     ('Pajustiku tee', 'Pirita'),
     ('Pakase tn', 'Haabersti'),
     ('Palderjani tee', 'Pirita'),
     ('Paldiski maantee', 'Kesklinn'),
     ('Paljandi tn', 'Haabersti'),
     ('Paljassaare põik', 'Põhja-Tallinn'),
     ('Paljassaare tee', 'Põhja-Tallinn'),
     ('Pallasti tn', 'Lasnamäe'),
     ('Palli tn', 'Nõmme'),
     ('Palu tn', 'Nõmme'),
     ('Palusambla tn', 'Nõmme'),
     ('Paneeli tn', 'Lasnamäe'),
     ('Panga tn', 'Lasnamäe'),
     ('Papli tn', 'Pirita'),
     ('Paplite puiestee', 'Nõmme'),
     ('Parda tn', 'Kesklinn'),
     ('Pardi tn', 'Kristiine'),
     ('Pardiloigu tn', 'Põhja-Tallinn'),
     ('Pargi tn', 'Nõmme'),
     ('Parmu tn', 'Mustamäe'),
     ('Parve tn', 'Haabersti'),
     ('Patriarh Aleksius II väljak', 'Lasnamäe'),
     ('Paul Kerese tn', 'Nõmme'),
     ('Paul Pinna tn', 'Lasnamäe'),
     ('Pebre tn', 'Põhja-Tallinn'),
     ('Pedaja tn', 'Nõmme'),
     ('Peeter Süda tn', 'Kesklinn'),
     ('Peetri tn', 'Põhja-Tallinn'),
     ('Pelguranna tn', 'Põhja-Tallinn'),
     ('Pesa tn', 'Nõmme'),
     ('Peterburi tee', 'Lasnamäe'),
     ('Petrooleumi tn', 'Kesklinn'),
     ('Pidu tn', 'Nõmme'),
     ('Pihlaka tn', 'Nõmme'),
     ('Pihlametsa tee', 'Pirita'),
     ('Piibelehe tn', 'Haabersti'),
     ('Piibri tn', 'Nõmme'),
     ('Piima tn', 'Kesklinn'),
     ('Piiri tn', 'Nõmme'),
     ('Piiritsa tn', 'Haabersti'),
     ('Piiskopi tn', 'Kesklinn'),
     ('Pikaliiva tn', 'Haabersti'),
     ('Pikk jalg', 'Kesklinn'),
     ('Pikk tn', 'Kesklinn'),
     ('Pikksilma tn', 'Kesklinn'),
     ('Pikri tn', 'Lasnamäe'),
     ('Pikse tn', 'Haabersti'),
     ('Piksepeni tn', 'Pirita'),
     ('Pille tn', 'Kesklinn'),
     ('Pilliroo tn', 'Nõmme'),
     ('Pilve tn', 'Kesklinn'),
     ('Pilviku tn', 'Nõmme'),
     ('Pinu tn', 'Nõmme'),
     ('Pirita tee', 'Pirita'),
     ('Pirni tn', 'Kristiine'),
     ('Planeedi tn', 'Kesklinn'),
     ('Plangu tn', 'Nõmme'),
     ('Plasti tn', 'Lasnamäe'),
     ('Pohla tn', 'Nõmme'),
     ('Pojengi tee', 'Pirita'),
     ('Poldri tn', 'Kesklinn'),
     ('Poordi tn', 'Kesklinn'),
     ('Poru tn', 'Haabersti'),
     ('Postitalu tn', 'Haabersti'),
     ('Preesi tn', 'Põhja-Tallinn'),
     ('Prii tn', 'Nõmme'),
     ('Priimula tee', 'Pirita'),
     ('Priisle tee', 'Lasnamäe'),
     ('Printsu tee', 'Haabersti'),
     ('Pronksi tn', 'Kesklinn'),
     ('Puhangu tn', 'Põhja-Tallinn'),
     ('Puhke tn', 'Kesklinn'),
     ('Puhkekodu tee', 'Pirita'),
     ('Puhma tn', 'Nõmme'),
     ('Puju tn', 'Lasnamäe'),
     ('Puki tee', 'Pirita'),
     ('Punane tn', 'Lasnamäe'),
     ('Pune tee', 'Pirita'),
     ('Punga tn', 'Pirita'),
     ('Puraviku tn', 'Nõmme'),
     ('Purde tn', 'Pirita'),
     ('Purje tn', 'Pirita'),
     ('Puu tn', 'Nõmme'),
     ('Puusepa tn', 'Nõmme'),
     ('Puuvilja tn', 'Nõmme'),
     ('Puuvilla tn', 'Põhja-Tallinn'),
     ('Päevakoera tn', 'Pirita'),
     ('Pähkli tn', 'Pirita'),
     ('Päikese puiestee', 'Nõmme'),
     ('Pärituule tn', 'Haabersti'),
     ('Pärja tn', 'Nõmme'),
     ('Pärnade puiestee', 'Nõmme'),
     ('Pärnamäe tee', 'Pirita'),
     ('Pärnaõie tee', 'Pirita'),
     ('Pärniku tee', 'Pirita'),
     ('Pärnu maantee', 'Kesklinn'),
     ('Pärnulõuka tn', 'Põhja-Tallinn'),
     ('Pääsküla tn', 'Nõmme'),
     ('Pääsukese tn', 'Kesklinn'),
     ('Pääsusilma tee', 'Pirita'),
     ('Põdra tn', 'Nõmme'),
     ('Põdrakanepi tee', 'Pirita'),
     ('Põhja puiestee', 'Põhja-Tallinn'),
     ('Põhjakaare tn', 'Nõmme'),
     ('Põlde põik', 'Haabersti'),
     ('Põlde tn', 'Haabersti'),
     ('Põldma tn', 'Pirita'),
     ('Põldmarja tn', 'Haabersti'),
     ('Põlendiku tn', 'Haabersti'),
     ('Põllu põik', 'Nõmme'),
     ('Põllu tn', 'Nõmme'),
     ('Põllumäe tn', 'Haabersti'),
     ('Põõsa tee', 'Pirita'),
     ('Pöörise tn', 'Mustamäe'),
     ('Pühavaimu tn', 'Kesklinn'),
     ('Püssirohu tn', 'Kesklinn'),
     ('Püü põik', 'Kristiine'),
     ('Püü tn', 'Kristiine'),
     ('Raadiku tn', 'Lasnamäe'),
     ('Raba tn', 'Nõmme'),
     ('Rabaküla tn', 'Mustamäe'),
     ('Rabaveere tn', 'Nõmme'),
     ('Raekoja plats', 'Kesklinn'),
     ('Raekoja tn', 'Kesklinn'),
     ('Rahe tn', 'Haabersti'),
     ('Rahu tee', 'Lasnamäe'),
     ('Rahu tn', 'Nõmme'),
     ('Rahukohtu tn', 'Kesklinn'),
     ('Rahumäe tee', 'Kristiine'),
     ('Rahvakooli tee', 'Pirita'),
     ('Raie tn', 'Nõmme'),
     ('Raja tn', 'Mustamäe'),
     ('Rajametsa tn', 'Nõmme'),
     ('Rajapere tn', 'Haabersti'),
     ('Rakise tn', 'Lasnamäe'),
     ('Randla tn', 'Põhja-Tallinn'),
     ('Randvere tee', 'Pirita'),
     ('Rangu tn', 'Haabersti'),
     ('Ranna tee', 'Pirita'),
     ('Rannamäe tee', 'Kesklinn'),
     ('Rannamõisa tee', 'Haabersti'),
     ('Rannaniidu tn', 'Haabersti'),
     ('Ranniku põik', 'Pirita'),
     ('Ranniku tee', 'Pirita'),
     ('Rao tn', 'Nõmme'),
     ('Rapla tn', 'Kesklinn'),
     ('Rataskaevu tn', 'Kesklinn'),
     ('Ratta tn', 'Nõmme'),
     ('Raua põik', 'Kesklinn'),
     ('Raua tn', 'Kesklinn'),
     ('Raudosja tee', 'Pirita'),
     ('Raudtee tn', 'Nõmme'),
     ('Ravi tn', 'Kesklinn'),
     ('Ravila tn', 'Nõmme'),
     ('Rebase tn', 'Nõmme'),
     ('Rebasesaba tee', 'Pirita'),
     ('Regati puiestee', 'Pirita'),
     ('Reha tn', 'Haabersti'),
     ('Rehe põik', 'Haabersti'),
     ('Rehe tn', 'Haabersti'),
     ('Reidi tee', 'Kesklinn'),
     ('Reisijate tn', 'Põhja-Tallinn'),
     ('Reketi tn', 'Kesklinn'),
     ('Remmelga tn', 'Nõmme'),
     ('Retke tee', 'Mustamäe'),
     ('Riida tn', 'Nõmme'),
     ('Riisika tn', 'Nõmme'),
     ('Risti tn', 'Nõmme'),
     ('Ristiku põik', 'Põhja-Tallinn'),
     ('Ristiku tn', 'Põhja-Tallinn'),
     ('Rivi tn', 'Kristiine'),
     ('Rocca al Mare tn', 'Haabersti'),
     ('Roheline aas', 'Kesklinn'),
     ('Roheline tn', 'Nõmme'),
     ('Rohu tn', 'Põhja-Tallinn'),
     ('Rohula tn', 'Nõmme'),
     ('Rohumaa tn', 'Haabersti'),
     ('Ronga tn', 'Kristiine'),
     ('Roo tn', 'Põhja-Tallinn'),
     ('Roolahe tn', 'Haabersti'),
     ('Roopa tn', 'Kesklinn'),
     ('Roosi tn', 'Nõmme'),
     ('Roosikrantsi tn', 'Kesklinn'),
     ('Roostiku tn', 'Haabersti'),
     ('Roseni tn', 'Kesklinn'),
     ('Rotermanni tn', 'Kesklinn'),
     ('Rudolf Tobiase tn', 'Kesklinn'),
     ('Rukki tn', 'Põhja-Tallinn'),
     ('Rukkilille tee', 'Pirita'),
     ('Rulli tn', 'Nõmme'),
     ('Rumbi tn', 'Kesklinn'),
     ('Rummu tee', 'Pirita'),
     ('Rutu tn', 'Kesklinn'),
     ('Ruunaoja tn', 'Lasnamäe'),
     ('Räga tn', 'Haabersti'),
     ('Rähkloo tn', 'Lasnamäe'),
     ('Rähni tn', 'Kristiine'),
     ('Räime tn', 'Haabersti'),
     ('Räitsaka tn', 'Haabersti'),
     ('Rändrahnu tee', 'Pirita'),
     ('Ränduri tn', 'Nõmme'),
     ('Rännaku puiestee', 'Nõmme'),
     ('Rästa põik', 'Kristiine'),
     ('Rästa tn', 'Kristiine'),
     ('Rätsepa tee', 'Pirita'),
     ('Rävala puiestee', 'Kesklinn'),
     ('Räägu tn', 'Kristiine'),
     ('Rõika tn', 'Haabersti'),
     ('Rõugu tn', 'Haabersti'),
     ('Rõõmu tn', 'Nõmme'),
     ('Ründi tn', 'Haabersti'),
     ('Rünga tn', 'Lasnamäe'),
     ('Rüütli tn', 'Kesklinn'),
     ('Saadu tn', 'Haabersti'),
     ('Saagi tn', 'Nõmme'),
     ('Saani tn', 'Põhja-Tallinn'),
     ('Saare tn', 'Pirita'),
     ('Saaremaa puiestee', 'Lasnamäe'),
     ('Saarepiiga puiestee', 'Lasnamäe'),
     ('Saarepuu tn', 'Nõmme'),
     ('Saariku tee', 'Pirita'),
     ('Saarma põik', 'Haabersti'),
     ('Saarma tn', 'Haabersti'),
     ('Saarvahtra puiestee', 'Nõmme'),
     ('Sadama tn', 'Kesklinn'),
     ('Saeveski tn', 'Nõmme'),
     ('Sagari tn', 'Haabersti'),
     ('Saha põik', 'Nõmme'),
     ('Saha tn', 'Nõmme'),
     ('Saiakang', 'Kesklinn'),
     ('Sakala tn', 'Kesklinn'),
     ('Saku tn', 'Kesklinn'),
     ('Salme tn', 'Põhja-Tallinn'),
     ('Salu tee', 'Pirita'),
     ('Salve tn', 'Nõmme'),
     ('Sambla tn', 'Nõmme'),
     ('Sambliku tn', 'Nõmme'),
     ('Sammu tn', 'Kristiine'),
     ('Sanatooriumi tn', 'Nõmme'),
     ('Sanglepa tn', 'Pirita'),
     ('Sarapiku tee', 'Pirita'),
     ('Sarapuu tn', 'Pirita'),
     ('Sarra tn', 'Haabersti'),
     ('Sarruse tn', 'Lasnamäe'),
     ('Sarve tn', 'Nõmme'),
     ('Saturni tn', 'Kesklinn'),
     ('Saue tn', 'Põhja-Tallinn'),
     ('Sauna tn', 'Kesklinn'),
     ('Saviliiva tee', 'Haabersti'),
     ('Seebi tn', 'Kristiine'),
     ('Seedri põik', 'Nõmme'),
     ('Seedri tn', 'Nõmme'),
     ('Seemne tn', 'Kristiine'),
     ('Seene tn', 'Nõmme'),
     ('Seli puiestee', 'Lasnamäe'),
     ('Selise tn', 'Haabersti'),
     ('Selja tn', 'Haabersti'),
     ('Seljaku tn', 'Nõmme'),
     ('Sepa tn', 'Põhja-Tallinn'),
     ('Sepapaja tn', 'Lasnamäe'),
     ('Sepapere tn', 'Haabersti'),
     ('Sepise tn', 'Lasnamäe'),
     ('Serva tn', 'Nõmme'),
     ('Side tn', 'Nõmme'),
     ('Siduri tn', 'Kesklinn'),
     ('Sihi tn', 'Nõmme'),
     ('Siia tn', 'Haabersti'),
     ('Siidisaba tn', 'Kristiine'),
     ('Siili tn', 'Mustamäe'),
     ('Siire tn', 'Haabersti'),
     ('Sikupilli tn', 'Lasnamäe'),
     ('Sikuti tn', 'Haabersti'),
     ('Silde tn', 'Lasnamäe'),
     ('Silgu tn', 'Haabersti'),
     ('Silikaltsiidi tn', 'Nõmme'),
     ('Silla tn', 'Nõmme'),
     ('Silluse tn', 'Lasnamäe'),
     ('Silmiku tn', 'Pirita'),
     ('Silmu tn', 'Haabersti'),
     ('Sinika tn', 'Kristiine'),
     ('Siniladva tee', 'Pirita'),
     ('Sinilille tn', 'Nõmme'),
     ('Sinimäe tn', 'Lasnamäe'),
     ('Sinirebase tn', 'Nõmme'),
     ('Sinitiiva tn', 'Pirita'),
     ('Sipelga tn', 'Mustamäe'),
     ('Sirbi tn', 'Põhja-Tallinn'),
     ('Sireli tn', 'Nõmme'),
     ('Sirge tn', 'Haabersti'),
     ('Sirptiiva tn', 'Pirita'),
     ('Sisaski tn', 'Nõmme'),
     ('Sitsi tn', 'Põhja-Tallinn'),
     ('Sitska tee', 'Pirita'),
     ('Sompa tee', 'Pirita'),
     ('Soo tn', 'Põhja-Tallinn'),
     ('Sookaskede puiestee', 'Nõmme'),
     ('Soolahe tee', 'Haabersti'),
     ('Soone põik', 'Nõmme'),
     ('Soone tn', 'Nõmme'),
     ('Sooranna tn', 'Haabersti'),
     ('Sooviku tn', 'Nõmme'),
     ('Soovildiku tn', 'Nõmme'),
     ('Soovõha tee', 'Pirita'),
     ('Spordi tn', 'Kristiine'),
     ('Staadioni tn', 'Kesklinn'),
     ('Staapli tn', 'Põhja-Tallinn'),
     ('Suislepa tee', 'Pirita'),
     ('Suitsu põik', 'Kesklinn'),
     ('Suitsu tn', 'Kesklinn'),
     ('Sule tn', 'Kristiine'),
     ('Sulevi tn', 'Nõmme'),
     ('Sulevimägi', 'Kesklinn'),
     ('Sumba tn', 'Haabersti'),
     ('Supluse puiestee', 'Pirita'),
     ('Suru tn', 'Pirita'),
     ('Suur Rannavärav', 'Kesklinn'),
     ('Suur-Ameerika tn', 'Kesklinn'),
     ('Suur-Karja tn', 'Kesklinn'),
     ('Suur-Kloostri tn', 'Kesklinn'),
     ('Suur-Laagri tn', 'Põhja-Tallinn'),
     ('Suur-Männiku tn', 'Nõmme'),
     ('Suur-Paala tn', 'Lasnamäe'),
     ('Suur-Patarei tn', 'Põhja-Tallinn'),
     ('Suur-Sõjamäe põik', 'Lasnamäe'),
     ('Suur-Sõjamäe tn', 'Lasnamäe'),
     ('Suurekivi tn', 'Pirita'),
     ('Suurevälja tn', 'Haabersti'),
     ('Suurtüki tn', 'Kesklinn'),
     ('Suusa tn', 'Nõmme'),
     ('Suve tn', 'Põhja-Tallinn'),
     ('Suvila tn', 'Nõmme'),
     ('Sädeme tn', 'Haabersti'),
     ('Säina tn', 'Haabersti'),
     ('Särje tn', 'Nõmme'),
     ('Särjesilma tn', 'Haabersti'),
     ('Sääse tn', 'Mustamäe'),
     ('Sõbra põik', 'Nõmme'),
     ('Sõbra tn', 'Nõmme'),
     ('Sõjakooli tn', 'Kristiine'),
     ('Sõle tn', 'Põhja-Tallinn'),
     ('Sõlme tn', 'Nõmme'),
     ('Sõmera tn', 'Põhja-Tallinn'),
     ('Sõnajala tn', 'Nõmme'),
     ('Sõpruse puiestee', 'Kristiine'),
     ('Sõpruse puiestee', 'Mustamäe'),
     ('Sõstra tn', 'Kristiine'),
     ('Sõstramäe tn', 'Lasnamäe'),
     ('Sõudebaasi tee', 'Haabersti'),
     ('Sõõru tn', 'Haabersti'),
     ('Söe tn', 'Kesklinn'),
     ('Söödi tn', 'Põhja-Tallinn'),
     ('Sügise tn', 'Põhja-Tallinn'),
     ('Sügislase tn', 'Pirita'),
     ('Süsta tn', 'Põhja-Tallinn'),
     ('Taara tn', 'Nõmme'),
     ('Taela tn', 'Haabersti'),
     ('Taevakivi tn', 'Lasnamäe'),
     ('Taevastiiva tn', 'Pirita'),
     ('Tagala tn', 'Haabersti'),
     ('Tagamaa tee', 'Kesklinn'),
     ('Taime tn', 'Põhja-Tallinn'),
     ('Tala tn', 'Lasnamäe'),
     ('Tallinna tn', 'Nõmme'),
     ('Taludevahe tn', 'Haabersti'),
     ('Talve tn', 'Nõmme'),
     ('Talviku tn', 'Kristiine'),
     ('Tambeti tn', 'Lasnamäe'),
     ('Tamme tn', 'Pirita'),
     ('Tammede puiestee', 'Nõmme'),
     ('Tammepärja tn', 'Nõmme'),
     ('Tammiku tn', 'Nõmme'),
     ('Tanuma tn', 'Haabersti'),
     ('Tapri tn', 'Lasnamäe'),
     ('Tare tn', 'Kesklinn'),
     ('Tarja tn', 'Pirita'),
     ('Tarna tn', 'Haabersti'),
     ('Tartu maantee', 'Kesklinn'),
     ('Tartu maantee', 'Lasnamäe'),
     ('Tasuja puiestee', 'Lasnamäe'),
     ('Tatari tn', 'Kesklinn'),
     ('Teaduspargi tn', 'Mustamäe'),
     ('Teatri väljak', 'Kesklinn'),
     ('Tedre põik', 'Kristiine'),
     ('Tedre tn', 'Kristiine'),
     ('Tedrepere tn', 'Haabersti'),
     ('Tehnika tn', 'Põhja-Tallinn'),
     ('Teisepere tn', 'Haabersti'),
     ('Teivi tn', 'Haabersti'),
     ('Telliskivi tn', 'Põhja-Tallinn'),
     ('Terase tn', 'Kesklinn'),
     ('Tervise tn', 'Kristiine'),
     ('Tihase tn', 'Kristiine'),
     ('Tihniku tn', 'Nõmme'),
     ('Tiigi tn', 'Nõmme'),
     ('Tiiru tn', 'Nõmme'),
     ('Tiiu tn', 'Kesklinn'),
     ('Tiiva tn', 'Kristiine'),
     ('Tildri põik', 'Mustamäe'),
     ('Tildri tn', 'Mustamäe'),
     ('Timuti tn', 'Põhja-Tallinn'),
     ('Tina tn', 'Kesklinn'),
     ('Tindi tn', 'Haabersti'),
     ('Tirgu tn', 'Haabersti'),
     ('Tiskre tee', 'Haabersti'),
     ('Tiskrevälja tn', 'Haabersti'),
     ('Tohu tn', 'Pirita'),
     ('Tolli tn', 'Kesklinn'),
     ('Tolmuka tee', 'Pirita'),
     ('Tondi tn', 'Kesklinn'),
     ('Tondiraba tn', 'Lasnamäe'),
     ('Toom-Kooli tn', 'Kesklinn'),
     ('Toom-Kuninga tn', 'Kesklinn'),
     ('Toom-Rüütli tn', 'Kesklinn'),
     ('Tooma tn', 'Lasnamäe'),
     ('Toomapere tn', 'Haabersti'),
     ('Toome puiestee', 'Nõmme'),
     ('Toome põik', 'Nõmme'),
     ('Toomiku tee', 'Pirita'),
     ('Toominga tn', 'Pirita'),
     ('Toompea tn', 'Kesklinn'),
     ('Toompuiestee', 'Kesklinn'),
     ('Toonela tee', 'Kesklinn'),
     ('Topi tn', 'Pirita'),
     ('Tormi tn', 'Kesklinn'),
     ('Torni tn', 'Nõmme'),
     ('Tornimäe tn', 'Kesklinn'),
     ('Torupilli ots', 'Kesklinn'),
     ('Trahteri tn', 'Haabersti'),
     ('Treiali tn', 'Põhja-Tallinn'),
     ('Trepi tn', 'Nõmme'),
     ('Trummi põik', 'Nõmme'),
     ('Trummi tn', 'Nõmme'),
     ('Tuha tn', 'Lasnamäe'),
     ('Tuhkru tn', 'Haabersti'),
     ('Tuisu tn', 'Kristiine'),
     ('Tuki tn', 'Haabersti'),
     ('Tulbi tn', 'Kristiine'),
     ('Tulekivi tn', 'Haabersti'),
     ('Tuleraua tn', 'Haabersti'),
     ('Tulika põik', 'Kristiine'),
     ('Tulika tn', 'Kristiine'),
     ('Tulimulla tn', 'Haabersti'),
     ('Tuluste tn', 'Haabersti'),
     ('Tungla tn', 'Nõmme'),
     ('Tupsi tee', 'Pirita'),
     ('Turba tn', 'Lasnamäe'),
     ('Turbasambla tn', 'Nõmme'),
     ('Tursa tn', 'Haabersti'),
     ('Turu plats', 'Nõmme'),
     ('Turu tn', 'Kesklinn'),
     ('Tuukri põik', 'Kesklinn'),
     ('Tuukri tn', 'Kesklinn'),
     ('Tuule tee', 'Pirita'),
     ('Tuulemaa tn', 'Põhja-Tallinn'),
     ('Tuulemäe tn', 'Lasnamäe'),
     ('Tuulenurga tn', 'Pirita'),
     ('Tuuleveski tn', 'Haabersti'),
     ('Tuuliku tee', 'Haabersti'),
     ('Tuvi tn', 'Kesklinn'),
     ('Tähe tn', 'Nõmme'),
     ('Tähesaju tee', 'Lasnamäe'),
     ('Tähetorni tn', 'Nõmme'),
     ('Täpiku tn', 'Pirita'),
     ('Tõivu tn', 'Lasnamäe'),
     ('Tõllu tn', 'Põhja-Tallinn'),
     ('Tõnismägi', 'Kesklinn'),
     ('Tõnu tn', 'Haabersti'),
     ('Tõru tn', 'Pirita'),
     ('Tõrviku tn', 'Lasnamäe'),
     ('Tõusu tee', 'Pirita'),
     ('Töökoja tn', 'Kesklinn'),
     ('Tööstuse tn', 'Põhja-Tallinn'),
     ('Türi tn', 'Kesklinn'),
     ('Tüve tn', 'Kristiine'),
     ('Ubalehe tee', 'Pirita'),
     ('Udeselja tn', 'Pirita'),
     ('Ugala tn', 'Nõmme'),
     ('Uime tn', 'Haabersti'),
     ('Ujuki tn', 'Haabersti'),
     ('Uku tn', 'Nõmme'),
     ('Umboja tn', 'Haabersti'),
     ('Uneliblika tn', 'Pirita'),
     ('Unna tn', 'Haabersti'),
     ('Urva tn', 'Pirita'),
     ('Ussilaka tee', 'Pirita'),
     ('Ussimäe tee', 'Lasnamäe'),
     ('Uue Maailma tn', 'Kesklinn'),
     ('Uuepere tn', 'Haabersti'),
     ('Uus tn', 'Kesklinn'),
     ('Uus-Kalamaja tn', 'Põhja-Tallinn'),
     ('Uus-Maleva tn', 'Põhja-Tallinn'),
     ('Uus-Sadama tn', 'Kesklinn'),
     ('Uus-Tatari tn', 'Kesklinn'),
     ('Uuslinna tn', 'Lasnamäe'),
     ('Uustalu tn', 'Haabersti'),
     ('Vaablase tn', 'Mustamäe'),
     ('Vaagi tn', 'Haabersti'),
     ('Vaalu tn', 'Haabersti'),
     ('Vaari tn', 'Kesklinn'),
     ('Vaarika tn', 'Kristiine'),
     ('Vaate põik', 'Pirita'),
     ('Vaate tee', 'Pirita'),
     ('Vabaduse puiestee', 'Nõmme'),
     ('Vabaduse väljak', 'Kesklinn'),
     ('Vabarna tee', 'Pirita'),
     ('Vabaõhukooli tee', 'Pirita'),
     ('Vabaõhumuuseumi tee', 'Haabersti'),
     ('Vabe tn', 'Haabersti'),
     ('Vabriku tn', 'Põhja-Tallinn'),
     ('Vahe tn', 'Nõmme'),
     ('Vahepere tn', 'Haabersti'),
     ('Vahtra tn', 'Nõmme'),
     ('Vahtramäe tee', 'Pirita'),
     ('Vahtriku tee', 'Pirita'),
     ('Vahulille tee', 'Pirita'),
     ('Vaigu tn', 'Nõmme'),
     ('Vaikne tn', 'Kesklinn'),
     ('Vaimu tn', 'Kesklinn'),
     ('Vainu tn', 'Nõmme'),
     ('Vainutalu põik', 'Haabersti'),
     ('Vainutalu tn', 'Haabersti'),
     ('Vaksiku tn', 'Pirita'),
     ('Valdeku tn', 'Nõmme'),
     ('Valge tn', 'Lasnamäe'),
     ('Valgevase tn', 'Põhja-Tallinn'),
     ('Valguse tn', 'Nõmme'),
     ('Valguta tn', 'Pirita'),
     ('Valli tn', 'Kesklinn'),
     ('Valukoja tn', 'Lasnamäe'),
     ('Valve tn', 'Nõmme'),
     ('Vambola tn', 'Kesklinn'),
     ('Vana turg', 'Kesklinn'),
     ('Vana-Kalamaja tn', 'Põhja-Tallinn'),
     ('Vana-Keldrimäe tn', 'Kesklinn'),
     ('Vana-Kuuli tn', 'Lasnamäe'),
     ('Vana-Liivamäe tn', 'Kesklinn'),
     ('Vana-Lõuna tn', 'Kesklinn'),
     ('Vana-Mustamäe tn', 'Nõmme'),
     ('Vana-Posti tn', 'Kesklinn'),
     ('Vana-Pärnu maantee', 'Nõmme'),
     ('Vana-Rannamõisa tee', 'Haabersti'),
     ('Vana-Tartu maantee', 'Kesklinn'),
     ('Vana-Umboja tn', 'Haabersti'),
     ('Vana-Veerenni tn', 'Kesklinn'),
     ('Vana-Viru tn', 'Kesklinn'),
     ('Vanakuu tn', 'Haabersti'),
     ('Vanaturu kael', 'Kesklinn'),
     ('Vanemuise põik', 'Nõmme'),
     ('Vanemuise tn', 'Nõmme'),
     ('Vaniku tn', 'Põhja-Tallinn'),
     ('Varbola tn', 'Nõmme'),
     ('Varese tn', 'Kristiine'),
     ('Variku tee', 'Pirita'),
     ('Varju tee', 'Pirita'),
     ('Varjulille tee', 'Pirita'),
     ('Varraku tn', 'Lasnamäe'),
     ('Varre tn', 'Kesklinn'),
     ('Varsaallika tn', 'Pirita'),
     ('Vasara tn', 'Põhja-Tallinn'),
     ('Vase tn', 'Kesklinn'),
     ('Vati tn', 'Kesklinn'),
     ('Vedru tn', 'Lasnamäe'),
     ('Veduri tn', 'Kesklinn'),
     ('Vee tn', 'Kesklinn'),
     ('Veerenni põik', 'Kesklinn'),
     ('Veerenni tn', 'Kesklinn'),
     ('Veeriku tee', 'Pirita'),
     ('Veerise tn', 'Haabersti'),
     ('Veetorni tn', 'Kesklinn'),
     ('Vene tn', 'Kesklinn'),
     ('Versta tn', 'Nõmme'),
     ('Vesikaare tn', 'Nõmme'),
     ('Vesilennuki tn', 'Põhja-Tallinn'),
     ('Vesioina tn', 'Nõmme'),
     ('Vesiravila tn', 'Haabersti'),
     ('Vesiveski tn', 'Pirita'),
     ('Vesivärava tn', 'Kesklinn'),
     ('Veski tn', 'Kesklinn'),
     ('Veskilise tn', 'Haabersti'),
     ('Veskimetsa tn', 'Haabersti'),
     ('Veskimäe tn', 'Haabersti'),
     ('Veskiposti tn', 'Kesklinn'),
     ('Vesse põik', 'Lasnamäe'),
     ('Vesse tn', 'Lasnamäe'),
     ('Vete tn', 'Nõmme'),
     ('Viadukti tn', 'Kesklinn'),
     ('Vibu tn', 'Põhja-Tallinn'),
     ('Videviku tn', 'Kesklinn'),
     ('Vigla tn', 'Haabersti'),
     ('Vihu tn', 'Haabersti'),
     ('Vihuri tn', 'Põhja-Tallinn'),
     ('Viidika tn', 'Haabersti'),
     ('Viige tn', 'Haabersti'),
     ('Viimsi põik', 'Pirita'),
     ('Viimsi tee', 'Pirita'),
     ('Viirpuu tee', 'Pirita'),
     ('Vikerkaare tn', 'Nõmme'),
     ('Vikerlase tn', 'Lasnamäe'),
     ('Vilisuu tn', 'Lasnamäe'),
     ('Viljandi maantee', 'Nõmme'),
     ('Villardi tn', 'Kesklinn'),
     ('Villem Reimani tn', 'Kesklinn'),
     ('Villkäpa tn', 'Pirita'),
     ('Vilu tee', 'Pirita'),
     ('Vimma tn', 'Haabersti'),
     ('Vindi tn', 'Kristiine'),
     ('Vineeri tn', 'Kesklinn'),
     ('Vinkli tn', 'Mustamäe'),
     ('Virbi tn', 'Lasnamäe'),
     ('Virmalise tn', 'Kesklinn'),
     ('Viru tn', 'Kesklinn'),
     ('Viru väljak', 'Kesklinn'),
     ('Virve tn', 'Kristiine'),
     ('Visase tn', 'Lasnamäe'),
     ('Vismeistri tn', 'Haabersti'),
     ('Viu tn', 'Kristiine'),
     ('Volta tn', 'Põhja-Tallinn'),
     ('Voo tn', 'Nõmme'),
     ('Voolu tn', 'Nõmme'),
     ('Voorimehe tn', 'Kesklinn'),
     ('Vormsi tn', 'Lasnamäe'),
     ('Vuti tn', 'Kristiine'),
     ('Vähi tn', 'Haabersti'),
     ('Väike Rannavärav', 'Kesklinn'),
     ('Väike tn', 'Nõmme'),
     ('Väike-Ameerika tn', 'Kesklinn'),
     ('Väike-Karja tn', 'Kesklinn'),
     ('Väike-Kloostri tn', 'Kesklinn'),
     ('Väike-Laagri tn', 'Põhja-Tallinn'),
     ('Väike-Männiku tn', 'Nõmme'),
     ('Väike-Paala tn', 'Lasnamäe'),
     ('Väike-Patarei tn', 'Põhja-Tallinn'),
     ('Väike-Pääsukese tn', 'Kesklinn'),
     ('Väike-Sõjamäe tn', 'Lasnamäe'),
     ('Väikese Illimari tn', 'Nõmme'),
     ('Väina tee', 'Pirita'),
     ('Välgu tn', 'Haabersti'),
     ('Välja tn', 'Kristiine'),
     ('Väo tee', 'Lasnamäe'),
     ('Väomurru tn', 'Lasnamäe'),
     ('Värava tn', 'Nõmme'),
     ('Värsi tn', 'Nõmme'),
     ('Värvi tn', 'Kristiine'),
     ('Västra tn', 'Haabersti'),
     ('Västriku tn', 'Kristiine'),
     ('Vääna tn', 'Nõmme'),
     ('Võidu põik', 'Nõmme'),
     ('Võidu tn', 'Nõmme'),
     ('Võidujooksu tn', 'Lasnamäe'),
     ('Võistluse tn', 'Kesklinn'),
     ('Võlvi tn', 'Kesklinn'),
     ('Võra tee', 'Pirita'),
     ('Võrgu tn', 'Põhja-Tallinn'),
     ('Võrgukivi tn', 'Haabersti'),
     ('Võrse tn', 'Kristiine'),
     ('Võru tn', 'Lasnamäe'),
     ('Võsa tee', 'Pirita'),
     ('Võsara tn', 'Haabersti'),
     ('Võsu tn', 'Nõmme'),
     ('Võtme tn', 'Kesklinn'),
     ('Vööri tn', 'Kesklinn'),
     ('Wismari tn', 'Kesklinn'),
     ('Ädala tn', 'Põhja-Tallinn'),
     ('Äigrumäe tee', 'Pirita'),
     ('Äkke tn', 'Haabersti'),
     ('Ääre tn', 'Nõmme'),
     ('Ääsi tn', 'Lasnamäe'),
     ('Õhtu tn', 'Nõmme'),
     ('Õie põik', 'Nõmme'),
     ('Õie tn', 'Nõmme'),
     ('Õilme tn', 'Kesklinn'),
     ('Õismäe tee', 'Haabersti'),
     ('Õitse tn', 'Nõmme'),
     ('Õle tn', 'Põhja-Tallinn'),
     ('Õllepruuli tn', 'Kesklinn'),
     ('Õnne tn', 'Nõmme'),
     ('Õpetajate tn', 'Kesklinn'),
     ('Õuna tn', 'Nõmme'),
     ('Ööbiku tn', 'Kristiine'),
     ('Öölase tn', 'Pirita'),
     ('Ülase tn', 'Kristiine'),
     ('Ülemiste tee', 'Lasnamäe'),
     ('Üliõpilaste tee', 'Mustamäe'),
     ('Ümera tn', 'Lasnamäe')]
